### ISSUE TITLE
Reference format differentiate in project config

### ISSUE THREAD

**Issue by fruex** [drwatson1/AspNet-WebApi#1]
To show a small difference in the Nuget Package Reference format and old packages.config let see differences in two project (ClassLibraryNugetConfig, ClassLibraryNugetPackageReference)

The first difference is that, after the installation of EntityFramework, in ClassLibraryNugetConfig App.config is created and configured.

The second difference is in ClassLibraryNugetConfig.csproj eg.
`<Import Project="..\packages\xunit.core.2.4.1\build\xunit.core.props" Condition="Exists('..\packages\xunit.core.2.4.1\build\xunit.core.props')" />`
but in ClassLibraryNugetPackageReference there is no Inport directive.

I figured that my test wasn't performed in NugetPackageReference format.

The link to repository https://github.com/fruex/drwatson1-AspNet-WebApi

**Comment by drwatson1** [comment]
According to [official documentation](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#package-compatibility-issues):

> With PackageReference, install.ps1 and uninstall.ps1 PowerShell scripts are not executed while installing or uninstalling a package.

I think this is the problem. Try to execute it manually. 

I'll see your project later and will try to help you.

**Comment by fruex** [comment]
Ok,

Let's figure it out how to feed parameters for `init.ps1`, `install.ps1` for `Entity Framework`
`param($installPath, $toolsPath, $package, $project)`

I just wanted to point out that it is a bit dangerous to use the new format, for many people who are attracted by this good pattern.

Maybe you'll provide an additional description for the project because it took me a few days to figure it out.

**Comment by drwatson1** [comment]
It is a good point. I'll add some information about these concerns in the description. Thank you for suggestion.

**Comment by drwatson1** [comment]
I've seen your project. As for an EntityFramework, I've added additional information to the [wiki](https://github.com/drwatson1/AspNet-WebApi/wiki#using-entityframework).
As for an xUnit, I don't use it, but as I can understand, you should add a reference to a "xunit.runner.visualstudio" package to make it works (but it hasn't any relation with the project template). It is described in the documentation [here](https://xunit.github.io/docs/getting-started/netfx/visual-studio):

> Important note: If you've previously installed the xUnit.net Visual Studio Runner VSIX (Extension), you must uninstall it first. The Visual Studio runner is only distributed via NuGet now. To remove it, to go Tools > Extensions and Updates. Scroll to the bottom of the list, and if xUnit.net is installed, uninstall it. This will force you to restart Visual Studio. 

> If you're having problems discovering or running tests, you may be a victim of a corrupted runner cache inside Visual Studio. To clear this cache, shut down all instances of Visual Studio, then delete the folder %TEMP%\VisualStudioTestExplorerExtensions. Also make sure your solution is only linked against a single version of the Visual Studio runner NuGet package (xunit.runner.visualstudio). 

> Right click on the project in Solution Explorer and choose Manage NuGet Packages. Search for (and install) a package named xunit.runner.visualstudio

Thank you for using my template. If you like it, please, star it on [Marketplace](https://marketplace.visualstudio.com/items?itemName=sergey-tregub.asp-net-web-api-owin-template) or this repo. Feel free to ask me any questions.
