### ISSUE TITLE
The API doesn't run on IIS 8 and higher

### ISSUE THREAD

**Issue by VlaSiv** [drwatson1/AspNet-WebApi#6]
I found that the default value for runAllManagedModulesForAllRequests is false (patch IIS 7 and high) and after deployment to IIS the API doesn't work\
So my suggestion is to add it explicitly in Web.config (line 52)
    <modules runAllManagedModulesForAllRequests="true">

**Comment by drwatson1** [comment]
I tried it myself with IIS 10.0 and found that it works. I can call any endpoint including swagger/ui/index.
I've published the project directly to IIS and it runs without any changes in a config file.

Can you add additional details to let me reproduce your problem? Do you use some other modules?

**Comment by drwatson1** [comment]
I close the issue as not reproducible but if you have additional information that can help me reproduce the problem feel free to open it again.
